# Site settings
title: Reagan Wang
email: reaganguan@gmail.com
description: > # keep this and put description below
  Technical Designer
url: "https://monkeyplato.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/reagan-wang"
github_username: Reagan-Wang
footer_text: "This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
