# Site settings
title: Poppy Li
email: poppy@mqs.com
description: > # keep this and put description below
  Technical and Creative Directory
url: "https://gamingportfolio.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/poppyli"
github_username: poppyli
twitter_username: poppylight
footer_text: "This is a parody/sample site for the character from the show <i>Mythic Quest</i>. This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
