# Site settings
title: Poppy Li
email: poppy@mqs.com
description: > # keep this and put description below
  Technical and Creative Director
url: "https://gamingportfolio.github.io" # the base hostname & protocol for your site
linkedin_url: "https://www.linkedin.com/in/poppyli.fake"
github_username: poppyli_fake
twitter_username: poppyli_fake
footer_text: "This is a parody site for the character from the show <i>Mythic Quest</i>. In no way do I claim any copyright. This site uses <a href='https://github.com/gamingportfolio/urban-theme-portfolio'>urban-theme (portfolio)</a>."

# Build settings
markdown: kramdown
permalink: pretty
